[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "PORT=$PORT npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
NODE_ENV = "production"
